<a href="https://colab.research.google.com/github/tr-nukala/pytorch-essential-training-deep-learning-2706322/blob/main/colab_notebooks/03_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Different ways to create tensors

In [1]:
import torch
import numpy as np

In [2]:
# initialize a tensor from a Python list
tensor_from_list=torch.tensor([1,2,3,4,5])
# initialize a tensor from a tuple
tensor_from_tuple=torch.tensor((6,7,8,9,10))
print("Tensor from list:",tensor_from_list)
print("Tensor from tuple:",tensor_from_tuple)

Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])


In [3]:
# initialize a tensor from a ndarray
tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))
print("Tensor from array:",tensor_from_array)

Tensor from array: tensor([11, 12, 13, 14, 15])


#### Different functions for creating tensors:
##### torch.empty(), torch.ones(), and torch.zeros()

In [4]:
tensor_emp = torch.empty(3,4)
print("tensor_emp :",tensor_emp)
tensor_zeros = torch.zeros(3,4)
print("tensor_zeros :",tensor_zeros)
tensor_ones= torch.ones(3,4)
print("tensor_ones :",tensor_ones)

tensor_emp : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
# tensors initialized by size with random values
# returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(4,5)
print("tensor_rand_un :",tensor_rand_un)
# returns a tensor filled with random numbers from a normal distribution
tensor_rand_norm = torch.randn(4,5)
print("tensor_rand_norm :",tensor_rand_norm)
# returns a tensor filled with random integers generated uniformly
tensor_rand_int = torch.randint(5,10,(4,5))
print("tensor_rand_int :",tensor_rand_int)

tensor_rand_un : tensor([[0.6391, 0.8820, 0.5191, 0.2258, 0.9734],
        [0.2181, 0.3085, 0.0819, 0.8647, 0.3126],
        [0.9671, 0.1838, 0.5938, 0.6768, 0.4668],
        [0.7462, 0.2997, 0.1865, 0.3199, 0.2472]])
tensor_rand_norm : tensor([[-1.3356,  1.5595,  0.4697,  0.9925,  1.4536],
        [ 0.9592,  0.1105,  0.4368, -1.4444, -1.2770],
        [-0.7763,  0.0814,  0.8071, -0.2035,  0.1676],
        [ 1.0258,  1.2963, -0.9140,  0.0566,  0.0159]])
tensor_rand_int : tensor([[5, 8, 9, 9, 8],
        [8, 6, 7, 9, 9],
        [8, 9, 7, 7, 9],
        [6, 6, 5, 9, 9]])


In [6]:
# initialize a tensor of ones
tensor_ones = torch.ones_like(tensor_rand_int)
print(tensor_ones)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


In [7]:


# Create a tensor with values from a normal distribution with mean = 5
tensor_with_mean_5 = torch.normal(mean=5, std=1, size=(2, 3))
print(tensor_with_mean_5)  # Values will be centered around 5

tensor([[3.8019, 5.6314, 4.8120],
        [6.1756, 2.8415, 5.8306]])


In [8]:


# Create a tensor with values from a normal distribution with std = 2
tensor_with_std_2 = torch.normal(mean=0, std=2, size=(2, 3))
print(tensor_with_std_2)  # Values will be more spread out

tensor([[ 3.0144, -0.5844,  1.8245],
        [-1.2047,  1.1381,  1.2134]])


In [10]:


# Generate heights with mean = 175 cm and std = 10 cm
heights = torch.normal(mean=175, std=10, size=(100,))
print(heights)

tensor([173.7807, 180.2596, 174.8199, 177.0205, 181.1580, 184.2496, 173.9381,
        171.3701, 167.6152, 176.0973, 170.0568, 174.7798, 176.5835, 171.0297,
        184.0435, 167.8916, 183.4122, 173.8812, 181.4492, 178.6461, 165.1304,
        156.9121, 178.3168, 162.6542, 184.8648, 162.6586, 171.9713, 150.3939,
        191.3448, 171.0468, 167.8795, 182.5518, 167.3751, 166.1567, 161.4302,
        159.5001, 183.0199, 177.9002, 175.4382, 180.5015, 178.4225, 170.2501,
        181.8301, 187.0603, 174.0932, 168.7491, 164.6570, 170.2088, 178.3634,
        173.3998, 182.5315, 160.7563, 176.3938, 184.6111, 181.8734, 178.3157,
        188.0307, 161.2532, 177.6318, 199.3980, 180.1310, 170.2273, 159.7941,
        172.1278, 178.4359, 164.1658, 164.2351, 156.4378, 184.7814, 162.6803,
        184.2559, 178.4521, 187.9033, 164.3248, 167.0565, 188.0524, 174.8226,
        187.9326, 185.3992, 190.6590, 171.5887, 180.8478, 175.2713, 170.8495,
        165.0887, 180.8761, 165.6303, 166.5849, 173.2512, 179.09

In [19]:
data_flt = torch.tensor([2., 4., 6., 8., 10.])
var_flt = torch.var(data_flt)
mean_flt = torch.mean(data_flt)
std_flt = torch.std(data_flt)

print(mean_flt)  # Output: tensor(6.0000)
print(var_flt)  # Output: tensor(2.0000)
print(std_flt)  # Output: tensor(2.8284)


data = torch.tensor([2, 4, 6, 8, 10])
std_tofloat = torch.std(data.float())
print(std_tofloat)

tensor(6.)
tensor(10.)
tensor(3.1623)
tensor(3.1623)
